FROM alpine:3

LABEL author="Helmi Pradita" maintainer="admin@helmipradita.dev"
LABEL company="HAEL DIGITAL CREATIVE" website="https://helmipradita.dev/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"